//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class JGuevaraProgramacionNCapasSeptiembre2025Entities : DbContext
    {
        public JGuevaraProgramacionNCapasSeptiembre2025Entities()
            : base("name=JGuevaraProgramacionNCapasSeptiembre2025Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carrera> Carreras { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
    
        public virtual int MateriaAdd(string nombre, Nullable<byte> creditos, Nullable<decimal> promedio, Nullable<decimal> dinero)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var creditosParameter = creditos.HasValue ?
                new ObjectParameter("Creditos", creditos) :
                new ObjectParameter("Creditos", typeof(byte));
    
            var promedioParameter = promedio.HasValue ?
                new ObjectParameter("Promedio", promedio) :
                new ObjectParameter("Promedio", typeof(decimal));
    
            var dineroParameter = dinero.HasValue ?
                new ObjectParameter("Dinero", dinero) :
                new ObjectParameter("Dinero", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MateriaAdd", nombreParameter, creditosParameter, promedioParameter, dineroParameter);
        }
    
        public virtual ObjectResult<MateriaGetById_Result> MateriaGetById(Nullable<int> idMateria)
        {
            var idMateriaParameter = idMateria.HasValue ?
                new ObjectParameter("IdMateria", idMateria) :
                new ObjectParameter("IdMateria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MateriaGetById_Result>("MateriaGetById", idMateriaParameter);
        }
    
        public virtual int MateriaChangeStatus(Nullable<int> id, Nullable<bool> status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MateriaChangeStatus", idParameter, statusParameter);
        }
    
        public virtual ObjectResult<CarreraGetAll_Result> CarreraGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CarreraGetAll_Result>("CarreraGetAll");
        }
    
        public virtual ObjectResult<MateriaGetAll_Result> MateriaGetAll(string nombre, Nullable<int> idCarrera)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var idCarreraParameter = idCarrera.HasValue ?
                new ObjectParameter("IdCarrera", idCarrera) :
                new ObjectParameter("IdCarrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MateriaGetAll_Result>("MateriaGetAll", nombreParameter, idCarreraParameter);
        }
    }
}
