//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<byte> Creditos { get; set; }
        public Nullable<decimal> Promedio { get; set; }
        public Nullable<decimal> Dinero { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.DateTime> FechaYHora { get; set; }
        public Nullable<int> IdCarrera { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual Carrera Carrera { get; set; }
    }
}
